export default {
    ok: "OK",
    cancel: "Cancel",
    accept: "Accept",
    deny: "Deny",
    buy: "Buy",
    sell: "Sell",
    share: "Share",
    add: "Add",
    invite: "Invite",
    create: "Create",
    offer: "Offer",
    inspect: "Inspect",
    map: "Map",
    whisper: "Whisper",
    say: "Say",
    zap: "Zap",
    use: "Use",
    open: "Open",
    settings: "Settings",
    shortcuts: "Shortcuts",
    menu: "Menu",
    music: "Music",
    sounds: "Sounds",
    inventory: "Inventory",
    chat: "Chat",
    message: "Message",
    duel: "Duel",
    mark: "Mark",
    gold: "Gold",
    silver: "Silver",
    copper: "Copper",
    empty: "Empty",

    moveUp: "Move Up",
    moveDown: "Move Down",
    moveLeft: "Move Left",
    moveRight: "Move Right",
    turnOnAutoAttack: "Auto Attack",
    zoomOut: "Zoom Out",
    zoomIn: "Zoom In",
    selectNearestTarget: "Select Nearest Target",
    openInventory: "Open InventoryWindow",
    openCharacterWindow: "Open Character Window",
    turnOnViewMode: "Turn On View Mode",
    pickUpItem: "Pick Up Item",
    openMap: "Open Map",

    madBoar: "Mad Boar",
    madBoarDescription: "A raging boar that attacks anything that moves.",
    rabbit: "Rabbit",
    rabbitDescription: "A small, fast creature that prefers to flee rather than fight.",
    skime: "Skime",
    skimeDescription: "A jelly-like creature that slowly moves in search of food.",
    bear: "Bear",
    bearDescription: "A massive beast capable of tearing enemies apart with its claws.",

    werewolf: "Werewolf",
    werewolfDescription: "A human that turns into a beast under the full moon.",
    dwarf: "Dwarf",
    dwarfDescription: "A short but sturdy warrior, skilled with an axe.",
    elf: "Elf",
    elfDescription: "A graceful being with sharp eyesight and deadly accuracy in archery.",
    human: "Human",
    humanDescription: "A versatile and adaptive member of civilized races.",
    orc: "Orc",
    orcDescription: "A strong and ferocious warrior who favors brute force.",
    hobbit: "Hobbit",
    hobbitDescription: "A small and nimble folk who prefer a peaceful life.",
    vampire: "Vampire",
    vampireDescription: "An immortal creature that feeds on the blood of the living.",
    golem: "Golem",
    golemDescription: "A powerful being carved from stone or clay.",
    berserk: "Berserk",
    berserkDescription: "A warrior who enters a frenzy, greatly increasing their strength in battle.",
    fairy: "Fairy",
    fairyDescription: "A tiny magical being that dwells in forests.",
    ancientElf: "Ancient Elf",
    ancientElfDescription: "A wise and powerful being possessing ancient knowledge.",

    unknownPotion: "Potion of healing",
    unknownPotionDescription: "On use it heals for {minPower} - {maxPower} points.",
    slash: "Slash",
    slashDescription: "Hits enemy for {minDamage} - {maxDamage} damage.",

    cooldownMessage: "Ability is on cooldown.",
    tooFarMessage: "Target is too far.",
    noTargetMessage: "No target selected.",
    notEnoughManaMessage: "Not enough mana.",

    tree: "Tree",
    treeDescription: "How they get in the way during a duel.",
    grass: "Grass",
    grassDescription: "I hope no one gets dizzy from all the green.",
    dirt: "Dirt",
    dirtDescription: "The very dirt you never notice under your feet.",
    stone: "Stone",
    stoneDescription: "A durable mineral used for construction and weapons.",
    rock: "Rock",
    rockDescription: "A massive piece of stone.",
    mountain: "Mountain",
    mountainDescription: "A towering landform with snow-covered peaks.",
    water: "Water",
    waterDescription: "Not too dirty and fresh, but not safe for drinking.",
    darkness: "Darkness",
    darknessDescription: "You can't see anything.",

}