export default {
    ok: "OK",
    cancel: "Cancelar",
    accept: "Aceptar",
    deny: "Rechazar",
    buy: "Comprar",
    sell: "Vender",
    share: "Compartir",
    add: "Añadir",
    invite: "Invitar",
    create: "Crear",
    offer: "Ofrecer",
    inspect: "Inspeccionar",
    map: "Mapa",
    whisper: "Susurrar",
    say: "Decir",
    zap: "Zap",
    use: "Usar",
    open: "Abrir",
    settings: "Configuración",
    shortcuts: "Atajos",
    menu: "Menú",
    music: "Música",
    sounds: "Sonidos",
    inventory: "Inventario",
    chat: "Chat",
    message: "Mensaje",
    duel: "Duelo",
    mark: "Marcar",
    gold: "Oro",
    silver: "Plata",
    copper: "Cobre",
    empty: "Vacío",

    moveUp: "Mover arriba",
    moveDown: "Mover abajo",
    moveLeft: "Mover a la izquierda",
    moveRight: "Mover a la derecha",
    turnOnAutoAttack: "Activar ataque automático",
    zoomOut: "Alejar",
    zoomIn: "Acercar",
    selectNearestTarget: "Seleccionar objetivo más cercano",
    openInventory: "Abrir inventario",
    openCharacterWindow: "Abrir ventana de personaje",
    turnOnViewMode: "Activar modo de visualización",
    pickUpItem: "Recoger objeto",
    openMap: "Abrir mapa",

    madBoar: "Jabalí Enloquecido",
    madBoarDescription: "Un jabalí furioso que embiste a todo lo que se mueve.",
    unknownPotion: "Poción Desconocida",
    unknownPotionDescription: "Sus efectos son misteriosos, úsala con precaución.",
    slash: "Tajo",
    slashDescription: "Un golpe poderoso que inflige gran daño a los enemigos.",

    cooldownMessage: "La habilidad está en recarga.",
    tooFarMessage: "El objetivo está demasiado lejos.",
    noTargetMessage: "No hay objetivo seleccionado.",
    notEnoughManaMessage: "No hay suficiente maná."
}