export default {
    ok: "OK",
    cancel: "Annuler",
    accept: "Accepter",
    deny: "Refuser",
    buy: "Acheter",
    sell: "Vendre",
    share: "Partager",
    add: "Ajouter",
    invite: "Inviter",
    create: "Créer",
    offer: "Offrir",
    inspect: "Examiner",
    map: "Carte",
    whisper: "Chuchoter",
    say: "Dire",
    zap: "Foudroyer",
    use: "Utiliser",
    open: "Ouvrir",
    settings: "Paramètres",
    shortcuts: "Raccourcis",
    menu: "Menu",
    music: "Musique",
    sounds: "Sons",
    inventory: "Inventaire",
    chat: "Chat",
    message: "Message",
    duel: "Duel",
    mark: "Marquer",
    gold: "Or",
    silver: "Argent",
    copper: "Cuivre",
    empty: "Vide",

    moveUp: "Monter",
    moveDown: "Descendre",
    moveLeft: "Gauche",
    moveRight: "Droite",
    turnOnAutoAttack: "Activer l'attaque automatique",
    zoomOut: "Dézoomer",
    zoomIn: "Zoomer",
    selectNearestTarget: "Sélectionner la cible la plus proche",
    openInventory: "Ouvrir l'inventaire",
    openCharacterWindow: "Ouvrir la fenêtre de personnage",
    turnOnViewMode: "Activer le mode vue",
    pickUpItem: "Ramasser l'objet",
    openMap: "Ouvrir la carte",

    madBoar: "Sanglier Fou",
    madBoarDescription: "Un sanglier enragé qui charge tout ce qui bouge.",
    unknownPotion: "Potion Inconnue",
    unknownPotionDescription: "Les effets sont mystérieux, utilisez avec prudence.",
    slash: "Entaille",
    slashDescription: "Une attaque puissante infligeant de lourds dégâts.",

    cooldownMessage: "Capacité en recharge.",
    tooFarMessage: "La cible est trop éloignée.",
    noTargetMessage: "Aucune cible sélectionnée.",
    notEnoughManaMessage: "Pas assez de mana."
}