export default {
    ok: "OK",
    cancel: "Abbrechen",
    accept: "Akzeptieren",
    deny: "Ablehnen",
    buy: "Kaufen",
    sell: "Verkaufen",
    share: "Teilen",
    add: "Hinzufügen",
    invite: "Einladen",
    create: "Erstellen",
    offer: "Anbieten",
    inspect: "Untersuchen",
    map: "Karte",
    whisper: "Flüstern",
    say: "Sagen",
    zap: "Zap",
    use: "Benutzen",
    open: "Öffnen",
    settings: "Einstellungen",
    shortcuts: "Tastenkürzel",
    menu: "Menü",
    music: "Musik",
    sounds: "Geräusche",
    inventory: "Inventar",
    chat: "Chat",
    message: "Nachricht",
    duel: "Duell",
    mark: "Markieren",
    gold: "Gold",
    silver: "Silber",
    copper: "Kupfer",
    empty: "Leer",

    moveUp: "Nach oben bewegen",
    moveDown: "Nach unten bewegen",
    moveLeft: "Nach links bewegen",
    moveRight: "Nach rechts bewegen",
    turnOnAutoAttack: "Automatischen Angriff aktivieren",
    zoomOut: "Herauszoomen",
    zoomIn: "Hereinzoomen",
    selectNearestTarget: "Nächstes Ziel auswählen",
    openInventory: "Inventar öffnen",
    openCharacterWindow: "Charakterfenster öffnen",
    turnOnViewMode: "Ansichtsmodus aktivieren",
    pickUpItem: "Gegenstand aufheben",
    openMap: "Karte öffnen",

    madBoar: "Wütendes Wildschwein",
    madBoarDescription: "Ein rasendes Wildschwein, das alles angreift, was sich bewegt.",
    unknownPotion: "Unbekannter Trank",
    unknownPotionDescription: "Die Wirkung ist mysteriös, Vorsicht geboten.",
    slash: "Hieb",
    slashDescription: "Ein mächtiger Schlag, der schweren Schaden verursacht.",

    cooldownMessage: "Fähigkeit ist im Cooldown.",
    tooFarMessage: "Ziel ist zu weit entfernt.",
    noTargetMessage: "Kein Ziel ausgewählt.",
    notEnoughManaMessage: "Nicht genügend Mana."
}