export default {
    ok: "ОК",
    cancel: "Отмена",
    accept: "Принять",
    deny: "Отклонить",
    buy: "Купить",
    sell: "Продать",
    share: "Поделиться",
    add: "Добавить",
    invite: "Пригласить",
    create: "Создать",
    offer: "Предложить",
    inspect: "Осмотреть",
    map: "Карта",
    whisper: "Шёпот",
    say: "Сказать",
    zap: "Ударить",
    use: "Использовать",
    open: "Открыть",
    settings: "Настройки",
    shortcuts: "Ярлыки",
    menu: "Меню",
    music: "Музыка",
    sounds: "Звуки",
    inventory: "Инвентарь",
    chat: "Чат",
    message: "Сообщение",
    duel: "Дуэль",
    mark: "Отметить",
    gold: "Золото",
    silver: "Серебро",
    copper: "Медь",
    empty: "Пусто",

    moveUp: "Вверх",
    moveDown: "Вниз",
    moveLeft: "Влево",
    moveRight: "Вправо",
    turnOnAutoAttack: "Автоатака",
    zoomOut: "Уменьшить",
    zoomIn: "Увеличить",
    selectNearestTarget: "Выбрать ближайшую цель",
    openInventory: "Открыть инвентарь",
    openCharacterWindow: "Открыть окно персонажа",
    turnOnViewMode: "Включить режим обзора",
    pickUpItem: "Подобрать предмет",
    openMap: "Открыть карту",

    madBoar: "Бешеный кабан",
    madBoarDescription: "Бешеный кабан, нападающий на всё, что движется.",
    rabbit: "Кролик",
    rabbitDescription: "Маленький быстрый зверёк, предпочитающий убегать, а не драться.",
    skime: "Скайм",
    skimeDescription: "Желеобразное существо, медленно передвигающееся в поисках пищи.",
    bear: "Медведь",
    bearDescription: "Огромный зверь, способный разорвать противника своими когтями.",

    werewolf: "Оборотень",
    werewolfDescription: "Человек, превращающийся в зверя при полной луне.",
    dwarf: "Дварф",
    dwarfDescription: "Низкорослый, но крепкий воин, мастерски владеющий топором.",
    elf: "Эльф",
    elfDescription: "Грациозное создание с острым зрением и меткостью в стрельбе.",
    human: "Человек",
    humanDescription: "Гибкий и адаптивный представитель цивилизованных народов.",
    orc: "Орк",
    orcDescription: "Сильный и свирепый воин, предпочитающий грубую силу.",
    hobbit: "Хоббит",
    hobbitDescription: "Маленький, ловкий народец, предпочитающий мирную жизнь.",
    vampire: "Вампир",
    vampireDescription: "Бессмертное существо, питающееся кровью живых.",
    golem: "Голем",
    golemDescription: "Могущественное создание, вырезанное из камня или глины.",
    berserk: "Берсерк",
    berserkDescription: "Воин, впадающий в ярость, увеличивающую его силу в бою.",
    fairy: "Фея",
    fairyDescription: "Маленькое магическое существо, обитающее в лесах.",
    ancientElf: "Древний эльф",
    ancientElfDescription: "Мудрое и могущественное существо, обладающее древними знаниями.",


    unknownPotion: "Зелье лечения",
    unknownPotionDescription: "При использовании лечит на {0} - {1} очков здоровья.",
    slash: "Взмах",
    slashDescription: "Атакует врага взмахом меча и наносит {0} - {1} единиц урона.",

    cooldownMessage: "{0} на перезарядке.",
    tooFarMessage: "{0} слишком далеко.",
    noTargetMessage: "Нет цели.",
    notEnoughManaMessage: "Недостаточно маны.",


    tree: "Дерево",
    treeDescription: "Как же они мешают в дуэли.",
    grass: "Трава",
    grassDescription: "Надеюсь, ни у кого не рябит в глазах от зелёного?.",
    dirt: "Земля",
    dirtDescription: "Та самая грязь, что ты не замечаешь под своими ногами.",
    stone: "Камень",
    stoneDescription: "Прочный минерал, используемый для строительства и оружия.",
    rock: "Скала",
    rockDescription: "Огромный кусок камня.",
    mountain: "Гора",
    mountainDescription: "Огромное возвышение земной коры, покрытое снегами на вершине.",
    water: "Вода",
    waterDescription: "Не слишком грязная и пресная, но для питья не подойдёт.",
    darkness: "Тьма",
    darknessDescription: "Невозможно увидеть что-либо.",
}