export default {
    ok: "Լավ",
    cancel: "Չեղարկել",
    accept: "Ընդունել",
    deny: "Մերժել",
    buy: "Գնել",
    sell: "Վաճառել",
    share: "Կիսվել",
    add: "Ավելացնել",
    invite: "Հրավնել",
    create: "Ստեղծել",
    offer: "Առաջարկել",
    inspect: "Ստուգել",
    map: "Քարտեզ",
    whisper: "Հշկել",
    say: "Խոսել",
    zap: "Զափել",
    use: "Օգտագործել",
    open: "Բացել",
    settings: "Կարգավորումներ",
    shortcuts: "Կարճ ուղիներ",
    menu: "Մենյու",
    music: "Երաժշտություն",
    sounds: "Ձայներ",
    inventory: "Ինվենտար",
    chat: "Զրույց",
    message: "Հաղորդագրություն",
    duel: "Դուել",
    mark: "Նշում",
    gold: "Ոսկի",
    silver: "Արծաթ",
    copper: "Կոփեր",
    empty: "Դատարկ",

    moveUp: "Շարժվել վեր",
    moveDown: "Շարժվել ներքև",
    moveLeft: "Շարժվել ձախ",
    moveRight: "Շարժվել աջ",
    turnOnAutoAttack: "Ավտո հարձակում",
    zoomOut: "Զում-հեռացում",
    zoomIn: "Զում-հավաքում",
    selectNearestTarget: "Ընտրել մոտակա թիրախը",
    openInventory: "Բացել ինվենտարը",
    openCharacterWindow: "Բացել հերոսի պատուհանը",
    turnOnViewMode: "Միացնել դիտման ռեժիմը",
    pickUpItem: "Հավաքել տարրը",
    openMap: "Բացել քարտեզը",

    madBoar: "Մադ Բոա",
    madBoarDescription: "Հախենված գորգ, որը հարձակվում է ամեն ինչին:",
    unknownPotion: "Անհայտ դեղամթերք",
    unknownPotionDescription: "Անհայտ դեղամթերքի նկարագրություն: Հնարավոր է անսպասելի ազդեցություն ունենալ:",
    slash: "Սլեշ",
    slashDescription: "Հզոր հարված, որը էջում է հակառակորդին:",

    cooldownMessage: "Հմտությունը դեռ չէ պատրաստ:",
    tooFarMessage: "Թիրախը շատ հեռու է:",
    noTargetMessage: "Թիրախ ընտրվել չէ:",
    notEnoughManaMessage: "Բավական մանա չկա:"
}