export default {
    ok: "OK",
    cancel: "Cancel",
    accept: "Accept",
    deny: "Deny",
    buy: "Buy",
    sell: "Sell",
    share: "Share",
    add: "Add",
    invite: "Invite",
    create: "Create",
    offer: "Offer",
    inspect: "Inspect",
    map: "Map",
    whisper: "Whisper",
    say: "Say",
    zap: "Zap",
    use: "Use",
    open: "Open",
    settings: "Settings",
    shortcuts: "Shortcuts",
    menu: "Menu",
    music: "Music",
    sounds: "Sounds",
    inventory: "Inventory",
    chat: "Chat",
    message: "Message",
    duel: "Duel",
    mark: "Mark",
    gold: "Gold",
    silver: "Silver",
    copper: "Copper",
    empty: "Empty",

    moveUp: "Move Up",
    moveDown: "Move Down",
    moveLeft: "Move Left",
    moveRight: "Move Right",
    turnOnAutoAttack: "Auto Attack",
    zoomOut: "Zoom Out",
    zoomIn: "Zoom In",
    selectNearestTarget: "Select Nearest Target",
    openInventory: "Open Inventory",
    openCharacterWindow: "Open Character Window",
    turnOnViewMode: "Turn On View Mode",
    pickUpItem: "Pick Up Item",
    openMap: "Open Map",

    madBoar: "Mad Boar",
    madBoarDescription: "A furious boar that charges at anything in its path.",
    unknownPotion: "Potion of healing",
    unknownPotionDescription: "On use it heals for {minPower} - {maxPower} points.",
    slash: "Slash",
    slashDescription: "Hits enemy for {minDamage} - {maxDamage} damage.",

    cooldownMessage: "Ability is on cooldown.",
    tooFarMessage: "Target is too far.",
    noTargetMessage: "No target selected.",
    notEnoughManaMessage: "Not enough mana."
}