export default {
    ok: "OK",
    cancel: "Annulla",
    accept: "Accetta",
    deny: "Rifiuta",
    buy: "Compra",
    sell: "Vendi",
    share: "Condividi",
    add: "Aggiungi",
    invite: "Invita",
    create: "Crea",
    offer: "Offri",
    inspect: "Ispeziona",
    map: "Mappa",
    whisper: "Sussurra",
    say: "Dì",
    zap: "Scossa",
    use: "Usa",
    open: "Apri",
    settings: "Impostazioni",
    shortcuts: "Scorciatoie",
    menu: "Menu",
    music: "Musica",
    sounds: "Suoni",
    inventory: "Inventario",
    chat: "Chat",
    message: "Messaggio",
    duel: "Duello",
    mark: "Segna",
    gold: "Oro",
    silver: "Argento",
    copper: "Rame",
    empty: "Vuoto",

    moveUp: "Muovi su",
    moveDown: "Muovi giù",
    moveLeft: "Muovi a sinistra",
    moveRight: "Muovi a destra",
    turnOnAutoAttack: "Attiva auto-attacco",
    zoomOut: "Zoom indietro",
    zoomIn: "Zoom in",
    selectNearestTarget: "Seleziona il bersaglio più vicino",
    openInventory: "Apri inventario",
    openCharacterWindow: "Apri finestra personaggio",
    turnOnViewMode: "Attiva modalità visualizzazione",
    pickUpItem: "Raccogli oggetto",
    openMap: "Apri mappa",

    madBoar: "Cinghiale Pazzo",
    madBoarDescription: "Un cinghiale furioso che carica contro tutto ciò che si muove.",
    unknownPotion: "Pozione Sconosciuta",
    unknownPotionDescription: "Gli effetti sono misteriosi, usala con cautela.",
    slash: "Fendente",
    slashDescription: "Un colpo potente che infligge danni elevati ai nemici.",

    cooldownMessage: "Abilità in ricarica.",
    tooFarMessage: "Bersaglio troppo lontano.",
    noTargetMessage: "Nessun bersaglio selezionato.",
    notEnoughManaMessage: "Mana insufficiente."
}