export default {
    ok: "ОК",
    cancel: "Отмена",
    accept: "Принять",
    deny: "Отклонить",
    buy: "Купить",
    sell: "Продать",
    share: "Поделиться",
    add: "Добавить",
    invite: "Пригласить",
    create: "Создать",
    offer: "Предложить",
    inspect: "Осмотреть",
    map: "Карта",
    whisper: "Шёпот",
    say: "Сказать",
    zap: "Ударить",
    use: "Использовать",
    open: "Открыть",
    settings: "Настройки",
    shortcuts: "Ярлыки",
    menu: "Меню",
    music: "Музыка",
    sounds: "Звуки",
    inventory: "Инвентарь",
    chat: "Чат",
    message: "Сообщение",
    duel: "Дуэль",
    mark: "Отметить",
    gold: "Золото",
    silver: "Серебро",
    copper: "Медь",
    empty: "Пусто",

    moveUp: "Вверх",
    moveDown: "Вниз",
    moveLeft: "Влево",
    moveRight: "Вправо",
    turnOnAutoAttack: "Автоатака",
    zoomOut: "Уменьшить",
    zoomIn: "Увеличить",
    selectNearestTarget: "Выбрать ближайшую цель",
    openInventory: "Открыть инвентарь",
    openCharacterWindow: "Открыть окно персонажа",
    turnOnViewMode: "Включить режим обзора",
    pickUpItem: "Подобрать предмет",
    openMap: "Открыть карту",

    madBoar: "Бешеный кабан",
    madBoarDescription: "Бешеный кабан, нападающий на всё, что движется.",
    unknownPotion: "Зелье лечения",
    unknownPotionDescription: "При использовании лечит на {minPower} - {maxPower} очков здоровья.",
    slash: "Взмах",
    slashDescription: "Атакует врага взмахом меча и наносит {minDamage} - {maxDamage} единиц урона.",

    cooldownMessage: "Способность на перезарядке.",
    tooFarMessage: "Цель слишком далеко.",
    noTargetMessage: "Цель не выбрана.",
    notEnoughManaMessage: "Недостаточно маны."
}