export default {
    ok: "Добре",
    cancel: "Скасувати",
    accept: "Прийняти",
    deny: "Відхилити",
    buy: "Купити",
    sell: "Продати",
    share: "Поділитися",
    add: "Додати",
    invite: "Запросити",
    create: "Створити",
    offer: "Запропонувати",
    inspect: "Оглянути",
    map: "Карта",
    whisper: "Шепотіти",
    say: "Сказати",
    zap: "Ударити",
    use: "Використати",
    open: "Відкрити",
    settings: "Налаштування",
    shortcuts: "Шорткати",
    menu: "Меню",
    music: "Музика",
    sounds: "Звуки",
    inventory: "Інвентар",
    chat: "Чат",
    message: "Повідомлення",
    duel: "Дуель",
    mark: "Позначити",
    gold: "Золото",
    silver: "Срібло",
    copper: "Мідь",
    empty: "Порожньо",

    moveUp: "Рух вгору",
    moveDown: "Рух вниз",
    moveLeft: "Рух вліво",
    moveRight: "Рух вправо",
    turnOnAutoAttack: "Увімкнути автоатаку",
    zoomOut: "Зменшити зум",
    zoomIn: "Збільшити зум",
    selectNearestTarget: "Вибрати найближчу ціль",
    openInventory: "Відкрити інвентар",
    openCharacterWindow: "Відкрити вікно персонажа",
    turnOnViewMode: "Увімкнути режим перегляду",
    pickUpItem: "Підібрати предмет",
    openMap: "Відкрити карту",

    madBoar: "Божевільний кабан",
    madBoarDescription: "Лютуючий кабан, що нападає на все, що рухається.",
    unknownPotion: "Невідома зілля",
    unknownPotionDescription: "Ефект невідомий, будьте обережні.",
    slash: "Розріз",
    slashDescription: "Потужний удар, що завдає великих ушкоджень ворогам.",

    cooldownMessage: "Здібність на перезарядці.",
    tooFarMessage: "Ціль занадто далеко.",
    noTargetMessage: "Ціль не вибрана.",
    notEnoughManaMessage: "Недостатньо мани."
}